# Indent lines with tabs instead of spaces.
# It is personal preferece of developer to set tab width in IDE.
useTabs: true

# Specify the line length that the printer will wrap on.
# Adapt to bigger screens.
printWidth: 120
