on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: ${{ github.ref }}

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout & Dependencies
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Use Deno 1
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Build
      - name: Build
        shell: pwsh
        run: |
          ./script/pipeline/Build-Site.ps1

      # Deploy
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "build/dev/standalone-docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
